descriptionFormat: ''
handle: clothing
hasDimensions: false
hasProductTitleField: true
hasVariantTitleField: false
hasVariants: true
name: Clothing
productTitleFormat: ''
siteSettings:
  06f4e499-3cdc-4d64-aec2-9a7d3a143c75: # Happy Lager (en)
    hasUrls: true
    template: shop/products/_product
    uriFormat: 'shop/products/{slug}'
skuFormat: ''
titleFormat: '{product.title}'
