contentColumnType: string
fieldGroup: 0d0b7e16-8d7c-4d6f-9059-d11c473058f4 # General
handle: myKlaviyolist
instructions: ''
name: 'My Klaviyo List'
searchable: false
translationKeyFormat: null
translationMethod: none
type: fostercommerce\klaviyoconnect\fields\ListField
